name: Buildings
version: '0.0.1'
main: ru.laimcraft.buildings.BuildingsPlugin
api-version: '1.21'
load: STARTUP
softdepend: [ DataBase, API, ProtocolLib, Citizens, WorldEdit, Vehicles, GSit, CoreProtect ]
authors: [ LaimCraft, isaevisa05 ]
website: https://github.com/LaimCraft
commands:
  construction:
    permission: buildings.construction
    usage: "/construction"
    aliases:
      - construction
      - const
      - c